# -*- coding: utf-8 -*-
"""K-MC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSf5CEK6FzhQ6IGY8eI77BBMlAFXmlcm
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, davies_bouldin_score
import matplotlib.pyplot as plt

import kagglehub
path = kagglehub.dataset_download("shwetabh123/mall-customers")

import os
data = pd.read_csv(os.path.join(path, 'Mall_Customers.csv'))

# Select features
X = data[['Annual Income (k$)', 'Spending Score (1-100)']]

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Elbow Method
wcss = []
for i in range(1, 11):
  kmeans = KMeans(n_clusters=i, random_state=42)
  kmeans.fit(X_scaled)
  wcss.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

# Apply K-Means
k = 5
kmeans = KMeans(n_clusters=k, random_state=42)
labels = kmeans.fit_predict(X_scaled)

# Evaluation Metrics
sil_score = silhouette_score(X_scaled, labels)
db_score = davies_bouldin_score(X_scaled, labels)
print("Silhouette Score:", sil_score)
print("Davies-Bouldin Index:", db_score)

# Visualization
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=labels, cmap='viridis')
plt.scatter(kmeans.cluster_centers_[:, 0],
kmeans.cluster_centers_[:, 1],
s=200, c='red', marker='X')
plt.title('Customer Segments')
plt.xlabel('Income')
plt.ylabel('Spending Score')
plt.show()

