# -*- coding: utf-8 -*-
"""Linear Regression using ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm6GIbYeiJuGHMc_5j7Ag6WQTdfXEcFn
"""

from sklearn.datasets import fetch_california_housing
import pandas as pd

california = fetch_california_housing()

df = pd.DataFrame(data = california.data, columns=california.feature_names)
df['target'] = california.target
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Population'], bins=30, kde=True)
plt.xlabel('Population')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

df.plot(kind = 'scatter',x = 'HouseAge',y = 'target',title = 'HouseAge vs target',figsize=(8, 6))
plt.show()

df.isnull().sum()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
print(df_scaled[:5])

from sklearn.model_selection import train_test_split
x,y = df_scaled, df['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, shuffle=True)

X_train

y_train

X_test

y_test

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predictions)
print(f'Mean Absolute Error: {mae}')

from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(y_test, predictions)
print(f'Root Mean Squared Error: {rmse}')