# -*- coding: utf-8 -*-
"""S_P_P.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rdWCPYtpcx2eiFYab9xKuyJ_FQvYIsg
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

import kagglehub
path = kagglehub.dataset_download("haseebindata/student-performance-predictions")

# Features and target
import os
print(os.listdir(path))
data = pd.read_csv(f'{path}/student_performance_updated_1000.csv')
print(data.columns)
X = data[['StudyHoursPerWeek', 'PreviousGrade', 'Attendance (%)']]
y = data['FinalGrade']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)

# Train model
model = LinearRegression()

# Combine X_train and y_train to drop NaNs consistently across both
train_data_combined = pd.concat([X_train, y_train], axis=1)
train_data_cleaned = train_data_combined.dropna()

X_train_cleaned = train_data_cleaned[X_train.columns]
y_train_cleaned = train_data_cleaned[y_train.name]

model.fit(X_train_cleaned, y_train_cleaned)

# Predictions
y_pred = model.predict(X_test_cleaned)

# Evaluation
mae = mean_absolute_error(y_test_cleaned, y_pred)
mse = mean_squared_error(y_test_cleaned, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_cleaned, y_pred)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

# Visualization (Actual vs Predicted)
plt.scatter(y_test_cleaned, y_pred)
plt.xlabel("Actual Scores")
plt.ylabel("Predicted Scores")
plt.title("Actual vs Predicted Student Performance")
plt.show()

